name: 'Update package file'
description: 'update version in package.json'
inputs:
  ref:
    description: 'Branch to update package.json on'
    required: true
runs:
  using: 'node12'
  main: 'index.js'