name: 'Test'
description: 'Create a release branch'
# inputs:
#   tag:
#     description: 'Version tag'
#     required: true
outputs:
  branch-name:
    description: 'Release branch name'
runs:
  using: 'node12'
  main: 'index.js'