name: Create Release

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  release_job:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    name: A job that creates a tag
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
