name: Test Action

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: Test Action
      id: test
      uses: ./.github/actions/test-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        who-to-greet: 'Glen the Codemonger'
        tag: 'v1.0.0'
    - name: Get output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"