name: Test Action

on: [push]

env: 
  tag: 'v1.0.2'

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job that creates a release
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: Create release branch
      id: release-branch
      uses: ./.github/actions/test-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # with:
      #   tag: version.tag
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.release-branch.outputs.branch-name }}
    - name: Update package.json
      uses: ./.github/actions/update-package-file
      # with:
      #   tag: version.tag