name: Test Action

on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: Create release branch
      id: release-branch
      uses: ./.github/actions/test-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: 'v1.0.1'
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.release-branch.outputs.branch-name }}
    - name: Update package.json
      run: echo "Release branch is ${{ steps.release-branch.outputs.branch-name }}"